[package]
id = "5e5702e8-0d38-4e8a-b79c-1014aa4f0884"
name = "Skip developer logos"
version = "1.0.1"
authors = ["Alex Bates <alex@nanaian.town>"]
description = "Skips developer logos on startup"
license = "CC-BY-SA-4.0"
keywords = ["qol"]

[[dependencies]]
type = "decomp"
rev = "d830988ef9595c8bc064bf867d0793c1eef36da7"
