[package]
id = "ca7446f9-6b5e-4899-b414-716c2354eb88"
name = "Fix Electro Pop"
version = "1.0.1"
authors = ["Alex Bates <alex@nanaian.town>"]
description = "Fixes bug where Electro Pop sets FP to HP+15 rather than FP+15"
license = "CC-BY-SA-4.0"
keywords = ["bugfix"]

[[dependencies]]
type = "decomp"
rev = "159384c709698e18c9f89b4e5d38ab34ac88ab17"
